tree 実績情報 = {
	クリアＡ　海から　　　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／海" },
		説明 = "Main story route. Land in the Demon Realm from the sea and defeat the Demon Lord Kayblis",
	},
	クリアＡ　空から　　　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／空" },
		説明 = "Main story route. Have Toppos pull the castle and ram the enemy base, defeating Kayblis",
	},
	クリアＡ　強行突破　　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／強行" },
		説明 = "Main story route. Break through the Demon Realm with only the Anti-Demon Army, repel several Demon Lords, and defeat Kayblis",
	},
	クリアＡ　魔物界大侵攻　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／魔物界" },
		説明 = "Main story route. After retaking all regions, invade the Demon Realm with all humanity forces and defeat Kayblis during the chaos",
	},
	クリアＢ　魔王を倒したが　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／魔王を倒したが" },
		説明 = "Incomplete. Defeated the Demon Lord Kayblis, but...",
	},
	クリアＢ　タイムカプセル　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／タイムカプセル" },
		説明 = "Incomplete. Put the Demon Lord into a time capsule, but the demon army approached...",
	},
	クリアＢ　地底大作戦　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／地底" },
		説明 = "Incomplete. Attempted to reach the enemy base through the underground, but time ran out and Miki became the Demon Lord...",
	},
	クリアＢ　魔王美樹　　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／魔王美樹" },
		説明 = "Incomplete. Defeated Kayblis, but Demon Lord Miki awakened...",
	},
	クリアＢ　神の真実　　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／女神" },
		説明 = "Incomplete. Challenged the gods, but due to insufficient preparation you were crushed by the Goddess...",
	},
	クリアＢ　異界の魔王　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／異界の魔王" },
		説明 = "Incomplete. Demon Lord Miki appeared leading a Steel Horror army...",
	},
	クリアＣ　魔王ケイブリス　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／魔王ケイブリス" },
		説明 = "Bad end. The world now belongs to Kayblis...",
	},
	クリアＣ　勇者の成就　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／勇者" },
		説明 = "Bad end. The Hero achieved fulfillment, but the world...",
	},
	クリアＣ　人類滅亡　　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／人類滅亡" },
		説明 = "Bad end. All major regions were seized by the demon army and humanity was defeated...",
	},
	クリアＣ　敗北　　　　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／本戦敗北" },
		説明 = "Bad end. Unfortunately, the current Rance party couldn't win...",
	},
	"達成(クリア時)　初クリア　　　　　　★継続プレイ解放" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "ルート／初クリア" },
		説明 = "You can select CP bonuses from the next run onward",
	},
	達成　？？解放条件全達成　　　　　　★２部解放 = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "ルート／第２部解放" },
		隠し表示 = 1,
		説明 = "All ?? unlock conditions have been met, enabling Part 2",
	},
	"達成(第２部クリア時)　全クリア" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "ルート／第２部クリア" },
		隠し表示 = 1,
		説明 = "The Rance series fully concludes. Thank you",
	},
	達成　実績２０個　　　　　　　　　　★物理倍率＋１ = {
		種類 = 20,
		ボーナス = "物理倍率＋１",
		値 = 20,
		説明 = "Acquire 20 or more achievements total. Bonus (Permanent: Physical multiplier +1)",
	},
	達成　実績４０個　　　　　　　　　　★魔法倍率＋１ = {
		種類 = 20,
		ボーナス = "魔法倍率＋１",
		値 = 40,
		説明 = "Acquire 40 or more achievements total. Bonus (Permanent: Magic multiplier +1)",
	},
	達成　実績６０個　　　　　　　　　　★物理倍率＋１ = {
		種類 = 20,
		ボーナス = "物理倍率＋１",
		値 = 60,
		説明 = "Acquire 60 or more achievements total. Bonus (Permanent: Physical multiplier +1)",
	},
	達成　実績８０個　　　　　　　　　　★魔法倍率＋１ = {
		種類 = 20,
		ボーナス = "魔法倍率＋１",
		値 = 80,
		説明 = "Acquire 80 or more achievements total. Bonus (Permanent: Magic multiplier +1)",
	},
	達成　実績１００個　　　　　　　　　★物理倍率＋１ = {
		種類 = 20,
		ボーナス = "物理倍率＋１",
		値 = 100,
		説明 = "Acquire 100 or more achievements total. Bonus (Permanent: Physical multiplier +1)",
	},
	"達成(クリア時)　タイニリーチＥ　　　★レア確率ＵＰ" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／タイニリーチＥ" },
		説明 = "Obtain the Tiny Leech E treasure. Bonus (Permanent: Increased rare drop rate)",
	},
	"達成(クリア時)　マリアの可能性　　　●分岐発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／マリアと王子" },
		説明 = "Possibility that Dark Rance and Maria become lovers",
	},
	"達成(クリア時)　奈落の王　　　　　　●分岐発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／奈落の王" },
		説明 = "Possibility that the King of Heaven appears",
	},
	"達成(クリア時)　海獣　　　　　　　　★物理倍率＋１" = {
		種類 = 10,
		ボーナス = "物理倍率＋１",
		値 = (list) { "達成／海獣" },
		説明 = "Defeated the Sea Beast raid boss. Bonus (Permanent: Physical multiplier +1)",
	},
	"達成(クリア時)　怪獣　　　　　　　　★物理倍率＋１" = {
		種類 = 10,
		ボーナス = "物理倍率＋１",
		値 = (list) { "達成／怪獣" },
		説明 = "Defeated the Kaijuu UR. Bonus (Permanent: Physical multiplier +1)",
	},
	"達成(クリア時)　リーザス魔人２撃破　★異常レジスト＋１" = {
		種類 = 10,
		ボーナス = "異常レジスト＋１",
		値 = (list) { "達成／リーザス魔人２" },
		説明 = "Defeated two Demon Lords in the same turn in Rizeas. Bonus (Permanent: Status resist +1)",
	},
	"達成(クリア時)　ヘルマン魔人２撃破　★異常レジスト＋１" = {
		種類 = 10,
		ボーナス = "異常レジスト＋１",
		値 = (list) { "達成／ヘルマン魔人２" },
		説明 = "Defeated two Demon Lords in the same turn in Helman. Bonus (Permanent: Status resist +1)",
	},
	"達成(クリア時)　ゼス魔人２撃破　　　★異常レジスト＋１" = {
		種類 = 10,
		ボーナス = "異常レジスト＋１",
		値 = (list) { "達成／ゼス魔人２" },
		説明 = "Defeated two Demon Lords in the same turn in Zeth. Bonus (Permanent: Status resist +1)",
	},
	"達成(クリア時)　自由都市魔人２撃破　★異常レジスト＋１" = {
		種類 = 10,
		ボーナス = "異常レジスト＋１",
		値 = (list) { "達成／自由都市魔人２" },
		説明 = "Defeated two Demon Lords in the same turn in the Free Cities. Bonus (Permanent: Status resist +1)",
	},
	"達成(クリア時)　レイタイマン撃破　　★割り込み発生率＋１" = {
		種類 = 10,
		ボーナス = "割り込み発動＋１",
		値 = (list) { "達成／レイタイマン撃破" },
		説明 = "Rance defeated Demon Lord Ray in single combat. Bonus (Permanent: Interrupt rate +1)",
	},
	"達成(クリア時)　姉妹撃破　　　　　　★割り込み発生率＋１" = {
		種類 = 10,
		ボーナス = "割り込み発動＋１",
		値 = (list) { "達成／姉妹撃破" },
		説明 = "Defeated the Saizel-Hausel sisters. Bonus (Permanent: Interrupt rate +1)",
	},
	"達成(クリアＡ時)　ワンニャン　　　　★割り込み発生率＋１" = {
		種類 = 10,
		ボーナス = "割り込み発動＋１",
		値 = (list) { "達成／ケイブニャン" },
		説明 = "Chose “Kave-nyan” and cleared to the end. Bonus (Permanent: Interrupt rate +1)",
	},
	"達成(クリアＡ時)　恋人美樹　　　　　★割り込み発生率＋１" = {
		種類 = 10,
		ボーナス = "割り込み発動＋１",
		値 = (list) { "達成／恋人美樹" },
		説明 = "Cleared the game with Miki as Rance’s lover. Bonus (Permanent: Interrupt rate +1)",
	},
	"達成(クリア時)　リーザス解放　　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／リーザス解放" },
		説明 = "Base event (CP achievement effect activation) occurs. Rizeas army damage reduced by 10%",
	},
	"達成(クリア時)　リーザス４０枚　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／リーザス３３" },
		説明 = "Base event (CP achievement effect activation) occurs. Rizeas army damage reduced by 10%",
	},
	"達成(クリア時)　ヘルマン解放　　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／ヘルマン解放" },
		説明 = "Base event (CP achievement effect activation) occurs. Helman army damage reduced by 10%",
	},
	"達成(クリア時)　ヘルマン４０枚　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／ヘルマン３３" },
		説明 = "Base event (CP achievement effect activation) occurs. Helman army damage reduced by 10%",
	},
	"達成(クリア時)　ゼス解放　　　　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／ゼス解放" },
		説明 = "Base event (CP achievement effect activation) occurs. Zeth army damage reduced by 10%",
	},
	"達成(クリア時)　ゼス４０枚　　　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／ゼス３３" },
		説明 = "Base event (CP achievement effect activation) occurs. Zeth army damage reduced by 10%",
	},
	"達成(クリア時)　自由都市解放　　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／自由都市解放" },
		説明 = "Base event (CP achievement effect activation) occurs. Free Cities army damage reduced by 10%",
	},
	"達成(クリア時)　自由都市４０枚　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／自由都市３３" },
		説明 = "Base event (CP achievement effect activation) occurs. Free Cities army damage reduced by 10%",
	},
	"達成(クリア時)　ＪＡＰＡＮ４０枚　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／ＪＡＰＡＮ３３" },
		説明 = "Base event (CP achievement effect activation) occurs. Reduces human fatality rate",
	},
	"達成(クリア時)　その他４０枚　　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／その他３３" },
		説明 = "Base event (CP achievement effect activation) occurs. Reduces human fatality rate",
	},
	"達成(クリア時)　亜人４０枚　　　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／亜人３３" },
		説明 = "Base event (CP achievement effect activation) occurs. Reduces human fatality rate",
	},
	"達成(クリアＡ時)　４地域無事　　　　●？？解放条件" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "条件Ｘ／４地域無事" },
		説明 = "Part 2 unlocks once all ?? unlock requirements are fulfilled",
	},
	"達成(クリアＡ時)　ケイブリス撃破　　●？？解放条件" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "条件Ｘ／ケイブリス撃破" },
		説明 = "Part 2 unlocks once all ?? unlock requirements are fulfilled",
	},
	"達成(クリアＡ時)　ホーネット無事　　●？？解放条件" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "条件Ｘ／ホーネット無事" },
		説明 = "Part 2 unlocks once all ?? unlock requirements are fulfilled",
	},
	"達成(クリアＡ時)　魂管理局との邂逅　●？？解放条件" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "条件Ｘ／魂管理局との邂逅" },
		説明 = "Part 2 unlocks once all ?? unlock requirements are fulfilled",
	},
	"達成(クリアＡ時)　法王特典未使用　　●？？解放条件" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "条件Ｘ／法王特典未使用" },
		説明 = "Part 2 unlocks once all ?? unlock requirements are fulfilled",
	},
	"達成(２部クリア時)　親友は長田君" = {
		種類 = 10,
		値 = (list) { "ルート／長田君" },
		隠し表示 = 1,
		説明 = "You completed the adventure together with your best friend",
	},
	"達成(２部クリア時)　親友は志津香＆ナギ" = {
		種類 = 10,
		値 = (list) { "ルート／志津香＆ナギ" },
		隠し表示 = 1,
		説明 = "You completed the adventure together with your best friend",
	},
	"達成(２部クリア時)　親友はリセット" = {
		種類 = 10,
		値 = (list) { "ルート／リセット" },
		隠し表示 = 1,
		説明 = "You completed the adventure together with your best friend",
	},
	"達成(２部クリア時)　親友はザンス" = {
		種類 = 10,
		値 = (list) { "ルート／ザンス" },
		隠し表示 = 1,
		説明 = "You completed the adventure together with your best friend",
	},
	"達成(２部クリア時)　親友はウズメ" = {
		種類 = 10,
		値 = (list) { "ルート／ウズメ" },
		隠し表示 = 1,
		説明 = "You completed the adventure together with your best friend",
	},
	"達成(２部クリア時)　親友は乱義" = {
		種類 = 10,
		値 = (list) { "ルート／乱義" },
		隠し表示 = 1,
		説明 = "You completed the adventure together with your best friend",
	},
	"達成(２部クリア時)　親友は深根" = {
		種類 = 10,
		値 = (list) { "ルート／深根" },
		隠し表示 = 1,
		説明 = "You completed the adventure together with your best friend",
	},
	"達成(２部クリア時)　親友はミックス" = {
		種類 = 10,
		値 = (list) { "ルート／ミックス" },
		隠し表示 = 1,
		説明 = "You completed the adventure together with your best friend",
	},
	"達成(２部クリア時)　親友はスシヌ" = {
		種類 = 10,
		値 = (list) { "ルート／スシヌ" },
		隠し表示 = 1,
		説明 = "You completed the adventure together with your best friend",
	},
	"達成(２部クリア時)　親友は元就" = {
		種類 = 10,
		値 = (list) { "ルート／元就" },
		隠し表示 = 1,
		説明 = "You completed the adventure together with your best friend",
	},
	"達成(２部クリア時)　親友はレリコフ" = {
		種類 = 10,
		値 = (list) { "ルート／レリコフ" },
		隠し表示 = 1,
		説明 = "You completed the adventure together with your best friend",
	},
	"達成(２部クリア時)　親友はダークランス" = {
		種類 = 10,
		値 = (list) { "ルート／ダークランス" },
		隠し表示 = 1,
		説明 = "You completed the adventure together with your best friend",
	},
	"達成(２部クリア時)　親友はドッス＆ワッス" = {
		種類 = 10,
		値 = (list) { "ルート／ドッス＆ワッス" },
		隠し表示 = 1,
		説明 = "You completed the adventure together with your best friend",
	},
	"達成(２部クリア時)　親友は松下姫" = {
		種類 = 10,
		値 = (list) { "ルート／松下姫" },
		隠し表示 = 1,
		説明 = "You completed the adventure together with your best friend"
	},
	集結　ランスバリエーション = {
		種類 = 1,
		ボーナス = "",
		値 = (list) { "Lv42 ランス", "Lv45 ランス", "Lv65 ランス", "Lv55 ランス", "全裸 ランス", "タイニー ランス" },
	},
	集結　ランス城のメイドと騎士 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "ビスケッタ", "クリン", "ハイジ", "ロナ", "サーナキア", "クルーチェ" },
	},
	集結　運命の女１ = {
		種類 = 1,
		ボーナス = "",
		値 = (list) { "運命の女 フェリス", "運命の女 山本五十六", "運命の女 パステル", "運命の女 リア", "運命の女 マジック", "運命の女 志津香", "運命の女 戦姫" },
	},
	集結　運命の女２ = {
		種類 = 1,
		ボーナス = "",
		値 = (list) { "運命の女 毛利てる", "運命の女 ミラクル", "運命の女 シーラ", "運命の女 かなみ", "運命の女 チルディ", "運命の女 シィル" },
	},
	集結　フロストバイン一派 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "フロストバイン", "タマ", "あてな２号", "量産型あてな２号" },
	},
	集結　エターナルヒーロー = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "ブリティシュ", "カフェ", "日光", "魔剣 カオス", "ホ・ラガ" },
	},
	集結　ＡＬ教 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "クルックー", "ロードリング", "ＢＳ", "セル" },
	},
	集結　リーザス王家 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "リア", "マリス", "かなみ" },
	},
	集結　リーザス軍 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "バレス", "コルドバ", "エクス", "リック", "メナド", "キンケード", "チャカ", "アールコート" },
	},
	集結　リーザス親衛隊 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "レイラ", "チルディ", "ジュリア", "イベット" },
	},
	集結　ヘルマン共和国 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "シーラ", "ペルエレ", "フレイア" },
	},
	集結　ヘルマン軍 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "ヒューバート", "ロレックス", "アミトス", "クリーム", "トルストイ", "オルオレ" },
	},
	集結　パットン一派 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "パットン", "ハンティ", "キャンテル" },
	},
	集結　ゼス王国 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "マジック", "ガンジー", "カオル", "ウィチタ", "チョチョマン", "ウルザ" },
	},
	集結　ゼス軍 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "千鶴子", "アニス", "アレックス", "サイアス", "ウスピラ", "カバッハーン" },
	},
	"集結　カスタムの４魔女(R2)" = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "子供志津香", "マリア", "ミル", "エレノア" },
	},
	集結　７人の都市長 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "パパデマス", "パトリシア", "ビヨンホウ", "ペスポ", "エレノア", "コパンドン", "カチューシャ" },
	},
	集結　パランチョ王国 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "ポロン", "ピッテン" },
	},
	集結　ＪＰ毛利家 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "てる", "きく", "ちぬ" },
	},
	集結　ＪＰ上杉家 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "謙信", "愛", "勝子", "虎子" },
	},
	集結　妖怪軍団 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "政宗", "お町", "ノワール", "野菊", "折女", "黒部" },
	},
	集結　カラー一族 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "パステル", "サクラ", "イージス", "リセット", "フル", "ビビッド", "モダン" },
	},
	集結　ポピンズ一族 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "三菱王", "満鉄王", "日立姫", "東芝王子" },
	},
	集結　ホルス一族 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "テラ", "メガッス", "メガワス", "メガフォース" },
	},
	集結　聖魔教団 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "シーラ", "闘将Ａ", "闘将Ｂ", "闘将Ｃ", "ゼータ", "シグマ", "キャンテル" },
	},
	集結　マエリータ隊 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "王様", "剣豪", "アパッチ", "学者", "マッスル", "ニードル" },
	},
	集結　ハニー一族 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "ハニーキング", "ハニ子", "グリーンハニー", "ブルーハニー", "レッドハニー" },
	},
	集結　日本の人達 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "美樹", "健太郎", "大野喜郎さん", "長堀橋貞夫君", "東大寺久美" },
	},
	集結　ホーネット派 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "ホーネット", "サテラ", "ハウゼル", "シルキィ" },
	},
	集結　ケッセルのメイド達 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "アルカリア", "リリム", "加奈代", "エルシール", "シャロン", "ファーレン", "バーバラ", "パレロア" },
	},
	集結　聖女モンスター = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "ベゼルアイ大", "ウェンリーナー大", "セラクロラス大", "ハウセスナース大", "ベゼルアイ小", "ウェンリーナー小", "セラクロラス小", "ハウセスナース小" },
	},
	集結　ドット = {
		種類 = 1,
		ボーナス = "",
		値 = (list) { "タイニー ランス", "タイニー シィル", "タイニー ミラクル", "タイニー かなみ", "タイニー ピグ", "タイニー 志津香", "タイニー クルックー", "タイニー パステル" },
	},
	集結　ロードリングの成長 = {
		種類 = 1,
		ボーナス = "",
		値 = (list) { "Lv18 ロードリング", "Lv26 ロードリング", "Lv31 ロードリング", "Lv37 ロードリング" },
	},
	集結　女の子モンスター１ = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "きゃんきゃん", "フローズン", "メイドさん", "ラルカット", "９７チハ", "幸福きゃんきゃん", "体育スター" },
	},
	集結　女の子モンスター２ = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "シャチ子", "はいからちゃん", "ハチ女", "神風", "バルキリー", "マジスコ", "手裏剣使い" },
	},
	集結　女の子モンスター３ = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "男装女", "鉄腕ラブル", "ミイラン", "上野花子", "めぽら", "ガルバン" },
	},
	集結　次世代モンスター = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "命の次世代魔物", "大地の次世代魔物", "時の次世代魔物", "力の次世代魔物", "イカマン" },
	},
	"達成(アフター)　１クエスト達成　　　★自動戦闘倍率＋１" = {
		種類 = 10,
		ボーナス = "自動戦闘倍率＋１",
		値 = (list) { "達成／アフター１" },
		説明 = "Clear 1 or more challenge quests. Bonus (Permanent: Auto-battle multiplier +1)",
	},
	"達成(アフター)　２クエスト達成　　　★自動戦闘倍率＋１" = {
		種類 = 10,
		ボーナス = "自動戦闘倍率＋１",
		値 = (list) { "達成／アフター２" },
		説明 = "Clear 2 or more challenge quests. Bonus (Permanent: Auto-battle multiplier +1)",
	},
	"達成(アフター)　３クエスト達成　　　★自動戦闘倍率＋１" = {
		種類 = 10,
		ボーナス = "自動戦闘倍率＋１",
		値 = (list) { "達成／アフター３" },
		説明 = "Clear 3 or more challenge quests. Bonus (Permanent: Auto-battle multiplier +1)",
	},
	"達成(アフター)　４クエスト達成　　　★自動戦闘倍率＋１" = {
		種類 = 10,
		ボーナス = "自動戦闘倍率＋１",
		値 = (list) { "達成／アフター４" },
		説明 = "Clear 4 or more challenge quests. Bonus (Permanent: Auto-battle multiplier +1)",
	},
	"達成(アフター)　５クエスト達成　　　★自動戦闘倍率＋１" = {
		種類 = 10,
		ボーナス = "自動戦闘倍率＋１",
		値 = (list) { "達成／アフター５" },
		説明 = "Clear 5 or more challenge quests. Bonus (Permanent: Auto-battle multiplier +1)",
	},
	"達成(アフター)　６クエスト達成　　　★自動戦闘倍率＋１" = {
		種類 = 10,
		ボーナス = "自動戦闘倍率＋１",
		値 = (list) { "達成／アフター６" },
		説明 = "Clear 6 or more challenge quests. Bonus (Permanent: Auto-battle multiplier +1)",
	},
	"達成(アフター)　バスワルド　　　　　●キャラカード解放" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／バスワルド" },
		説明 = "Pacify the Class-2 God Baswald. Bonus (unrestricted mode: card appearance)",
	},
};